#!/bin/bash
PROJDIR=$(cd `dirname $0`/.. && pwd)
echo $PROJDIR 

VERSION="${1}"
TAG="v${VERSION}"
USER="leonardoaramaki"
REPO="gocat"
BINARY="${REPO}"

if [[ -z "${VERSION}" ]]; then
    echo "Usage: ${0} <version>"
    exit 1
fi

if [[ -z "${GITHUB_TOKEN}" ]]; then
    echo "You forgot to set your GITHUB_TOKEN"
    exit 2
fi

cd ${PROJDIR}

# Run the tests
# go test
# if [ $? -ne 0 ]; then
#     echo "Tests failed. Aborting."
#     exit 3
# fi

# Check if tag exists
git fetch --tags
git tag | grep "^${TAG}$"

if [ $? -ne 0 ]; then
    github-release release \
        --owner ${USER} \
        --repo ${REPO} \
        --tag ${TAG} \
        --release-name "${REPO} ${TAG}" \
        --body "${TAG}" \
        --prerelease
fi


for ARCH in "amd64" "386" "arm64"; do
    for OS in "darwin" "linux" "freebsd"; do
    
        if [ $ARCH == "386" -a $OS == "darwin" ]; then
            continue
        fi

        BINFILE="${BINARY}"

        if [[ "${OS}" == "windows" ]]; then
            BINFILE="${BINFILE}.exe"
        fi

        rm -f ${BINFILE}

        GOOS=${OS} GOARCH=${ARCH} go build github.com/${USER}/${REPO}

        if [[ "${OS}" == "windows" ]]; then
            ARCHIVE="${BINARY}-${OS}-${ARCH}-${VERSION}.zip"
            zip ${ARCHIVE} ${BINFILE}
        else
            ARCHIVE="${BINARY}-${OS}-${ARCH}-${VERSION}.tgz"
            tar --create --gzip --file=${ARCHIVE} ${BINFILE}
        fi

        echo "Uploading ${ARCHIVE}..."
        github-release upload \
            --owner ${USER} \
            --repo ${REPO} \
            --tag ${TAG} \
            --release-name "gocat ${VERSION}" \
            ${PROJDIR}/${ARCHIVE}
    done
done

